// =========================================================
// DOWNLOAD.JS — QR Prism v2.8
// PNG, JPG, SVG, WebP, 2×, 4×, PDF export
// Transparent background support per S.dlTransparent flag
// Author: Muhtasim Rahman (Turzo) · https://mdturzo.odoo.com
// =========================================================

function downloadQR(format) {
  const canvas = document.getElementById('qr-canvas');
  if (!canvas || canvas.style.display === 'none') {
    showToast('Generate a QR code first', 'info');
    return;
  }

  // Close dropdown
  document.getElementById('dl-dropdown')?.classList.remove('open');

  // Transparent mode: if S.dlTransparent is on, skip bg fill for formats that support it
  const useTransparent = S.dlTransparent && ['png', 'png2x', 'png4x', 'svg', 'webp'].includes(format);

  const base = `qrprism_${S.activeType || 'qr'}_${Date.now()}`;

  switch (format) {
    case 'png':
      _dlPNG(canvas, base + '.png', 1, useTransparent);
      break;
    case 'jpg':
      _dlJPG(canvas, base + '.jpg');          // JPG never transparent
      break;
    case 'webp':
      _dlWebP(canvas, base + '.webp', useTransparent);
      break;
    case 'png2x':
      _dlScaled(canvas, base + '_2x.png', 2, useTransparent);
      break;
    case 'png4x':
      _dlScaled(canvas, base + '_4x.png', 4, useTransparent);
      break;
    case 'svg':
      _dlSVG(canvas, base + '.svg', useTransparent);
      break;
    case 'pdf':
      _dlPDF(canvas, base + '.pdf');
      break;
    default:
      _dlPNG(canvas, base + '.png', 1, useTransparent);
  }
}

// ── PNG ────────────────────────────────────────────────────
function _dlPNG(canvas, name, quality = 1, transparent = false) {
  const src = transparent ? canvas : _withWhiteBG(canvas);
  const url = src.toDataURL('image/png', quality);
  triggerDownload(url, name);
  showToast('Downloaded PNG', 'success');
}

// ── JPG (always white bg) ──────────────────────────────────
function _dlJPG(canvas, name) {
  const url = _withWhiteBG(canvas).toDataURL('image/jpeg', 0.93);
  triggerDownload(url, name);
  showToast('Downloaded JPG', 'success');
}

// ── WebP ───────────────────────────────────────────────────
function _dlWebP(canvas, name, transparent = false) {
  const src = transparent ? canvas : _withWhiteBG(canvas);
  const url = src.toDataURL('image/webp', 0.92);
  triggerDownload(url, name);
  showToast('Downloaded WebP', 'success');
}

// ── Scaled PNG (2× / 4×) ──────────────────────────────────
function _dlScaled(canvas, name, scale, transparent = false) {
  const src = transparent ? canvas : _withWhiteBG(canvas);
  const tmp = document.createElement('canvas');
  tmp.width  = src.width  * scale;
  tmp.height = src.height * scale;
  const ctx  = tmp.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(src, 0, 0, tmp.width, tmp.height);
  const url = tmp.toDataURL('image/png');
  triggerDownload(url, name);
  showToast(`Downloaded ${scale}× PNG`, 'success');
}

// ── SVG (embeds PNG data URL as <image>) ───────────────────
function _dlSVG(canvas, name, transparent = false) {
  const src = transparent ? canvas : _withWhiteBG(canvas);
  const w   = src.width;
  const h   = src.height;
  const url = src.toDataURL('image/png');

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  ${transparent ? '' : `<rect width="${w}" height="${h}" fill="#ffffff"/>`}
  <image width="${w}" height="${h}" xlink:href="${url}"/>
</svg>`;

  const blob   = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const objUrl = URL.createObjectURL(blob);
  triggerDownload(objUrl, name);
  setTimeout(() => URL.revokeObjectURL(objUrl), 2000);
  showToast('Downloaded SVG', 'success');
}

// ── PDF (print dialog approach) ───────────────────────────
function _dlPDF(canvas, name) {
  // Build a printable page that auto-opens the print dialog
  const src = _withWhiteBG(canvas);
  const url = src.toDataURL('image/png');
  const w   = Math.min(src.width, 800);

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>QR Prism — Print</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      display: flex; flex-direction: column;
      align-items: center; justify-content: center;
      min-height: 100vh; background: #fff;
      font-family: 'Poppins', system-ui, sans-serif;
      padding: 32px;
    }
    img { max-width: ${w}px; width: 100%; height: auto; display: block; }
    p   { margin-top: 16px; font-size: 11pt; color: #555; }
    @media print {
      body { padding: 0; justify-content: flex-start; }
      p { display: none; }
    }
  </style>
</head>
<body>
  <img src="${url}" alt="QR Code">
  <p>Generated by QR Prism · <a href="https://muhtasim-rahman.github.io/qr-prism/">qrprism.app</a></p>
  <script>window.addEventListener('load', () => { setTimeout(() => window.print(), 400); });<\/script>
</body>
</html>`;

  const blob   = new Blob([html], { type: 'text/html' });
  const objUrl = URL.createObjectURL(blob);
  const win    = window.open(objUrl, '_blank', 'noopener');

  if (!win) {
    // Popup blocked — fall back to PNG
    _dlPNG(canvas, name.replace('.pdf', '.png'), 1, false);
    showToast('Popup blocked — downloaded PNG instead', 'warning');
  } else {
    showToast('Print dialog opened', 'info');
  }

  setTimeout(() => URL.revokeObjectURL(objUrl), 8000);
}

// ══════════════════════════════════════════════════════════
// HELPERS
// ══════════════════════════════════════════════════════════

/** Returns a new canvas with white background + original drawn on top */
function _withWhiteBG(canvas) {
  const tmp = document.createElement('canvas');
  tmp.width  = canvas.width;
  tmp.height = canvas.height;
  const ctx  = tmp.getContext('2d');
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, tmp.width, tmp.height);
  ctx.drawImage(canvas, 0, 0);
  return tmp;
}
